name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    - name: Build and test with Rake
      run: |
        gem install bundler
        sudo apt install -y libpq-dev libsqlite3-dev
        bundle install --jobs 4 --retry 3
        rails db:migrate RAILS_ENV=test
        node -v
        npm install yarn
        yarn install
        bundle exec rails webpacker:install
        bundle exec rails webpacker:compile
        bundle exec rake
