name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.4
    - name: Build and test with Rake
      run: |
        gem install bundler
        sudo apt install -y libpq-dev libsqlite3-dev
        bundle install --jobs 4 --retry 3
        rails db:migrate RAILS_ENV=test
        node -v
        echo $NODE_OPTIONS
        npm install yarn
        yarn install
        NODE_OPTIONS=--openssl-legacy-provider bundle exec rails webpacker:install
        NODE_OPTIONS=--openssl-legacy-provider bundle exec rails webpacker:compile
        bundle exec rake

